version: '3.2'

services:
  street_photo_flask:
    build:
      context: '../'
      dockerfile: 'docker/flask/Dockerfile'
    container_name: street_photo_flask
    expose:
      - "9000"
    ports:
      - 80:9000
    volumes:
    - ../flask-app/:/app/
    restart: always
