version: '3.2'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - street_photo_flask
    networks:
      - my-network
  street_photo_flask:
    build:
      context: '../'
      dockerfile: 'docker/flask/Dockerfile'
    container_name: street_photo_flask
    expose:
      - "9000"
    ports:
      - 9000:9000
    volumes:
      - ../:/app/
    restart: always
    networks:
      my-network:
        aliases:
          - photobooth.local

networks:
    my-network: